### ISSUE TITLE
adv clip encode needs to be updated

### ISSUE THREAD

**Issue by mizukarada** [TinyTerra/ComfyUI_tinyterraNodes#11]
Otherwise, SDXL checkpoints won't work.

**Comment by TinyTerra** [comment]
Latest push should fix this - let me know :)

**Comment by mizukarada** [comment]
Getting this error:
```log
!!! Exception during processing !!!
Traceback (most recent call last):
  File "D:\Users\Anon\Downloads\Programs\ComfyUI_windows_portable\ComfyUI\execution.py", line 144, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "D:\Users\Anon\Downloads\Programs\ComfyUI_windows_portable\ComfyUI\execution.py", line 74, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "D:\Users\Anon\Downloads\Programs\ComfyUI_windows_portable\ComfyUI\execution.py", line 67, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "D:\Users\Anon\Downloads\Programs\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_tinyterraNodes\tinyterraNodes.py", line
580, in adv_pipeloader
    positive_embeddings_final, pooled = advanced_encode(clip, positive, positive_token_normalization, positive_weight_interpretation, w_
max=1.0)
  File "D:\Users\Anon\Downloads\Programs\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_tinyterraNodes\adv_encode.py", line 260,
 in advanced_encode
    return prepareXL(embs_l, embs_g, pooled, clip_balance)
  File "D:\Users\Anon\Downloads\Programs\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_tinyterraNodes\adv_encode.py", line 235,
 in prepareXL
    return torch.cat([embs_l * l_w, embs_g * g_w], dim=-1), pooled
TypeError: expected Tensor as element 0 in argument 0, but got list

```

**Comment by TinyTerra** [comment]
Ohh okay, I see. I may need to add a new pipeKSampler node for XL conditioning - haven't been following the XL updates too closely, but I'll work on that now

**Comment by TinyTerra** [comment]
Let me know if the latest works for you

**Comment by mizukarada** [comment]
Thanks, it works.
