### ISSUE TITLE
(IMPORT FAILED)

### ISSUE THREAD

**Issue by Nico53425342** [TinyTerra/ComfyUI_tinyterraNodes#118]
Traceback (most recent call last):
  File "D:\Desktop\Comfy-UI+EX\ComfyUI\nodes.py", line 1879, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "D:\Desktop\Comfy-UI+EX\ComfyUI\custom_nodes\ComfyUI_tinyterraNodes\__init__.py", line 1, in <module>
    from .ttNpy.tinyterraNodes import TTN_VERSIONS
  File "D:\Desktop\Comfy-UI+EX\ComfyUI\custom_nodes\ComfyUI_tinyterraNodes\ttNpy\tinyterraNodes.py", line 54, in <module>
    from comfy_extras.chainner_models import model_loading
ModuleNotFoundError: No module named 'comfy_extras.chainner_models'

Cannot import D:\Desktop\Comfy-UI+EX\ComfyUI\custom_nodes\ComfyUI_tinyterraNodes module for custom nodes: No module named 'comfy_extras.chainner_models'

**Comment by 49RpK5dY** [comment]
Seems like a lot of custom nodes broke with latest ComfyUI update. You can rollback Comfy `git checkout ffc4b7c30e35eb2773ace52a0b00e0ca5c1f4362` until this get resolved.

**Comment by Nico53425342** [comment]
okay, thx for the command

**Comment by Nico53425342** [comment]
no more problem. thx
