### ISSUE TITLE
pipeKSampler error on latent upscale

### ISSUE THREAD

**Issue by mizukarada** [TinyTerra/ComfyUI_tinyterraNodes#12]
Using the `upscale_method` option in pipeKSampler throws this error:
```log
Traceback (most recent call last):
  File "D:\Users\Anon\Downloads\Programs\ComfyUI_windows_portable\ComfyUI\execution.py", line 144, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "D:\Users\Anon\Downloads\Programs\ComfyUI_windows_portable\ComfyUI\execution.py", line 74, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "D:\Users\Anon\Downloads\Programs\ComfyUI_windows_portable\ComfyUI\execution.py", line 67, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "D:\Users\Anon\Downloads\Programs\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_tinyterraNodes\tinyterraNodes.py",
 line 1190, in sample
    return process_sample_state(self, pipe, lora_name, lora_model_strength, lora_clip_strength, steps, cfg, sampler_name, schedule
r, denoise, image_output, preview_prefix, save_prefix, prompt, extra_pnginfo, my_unique_id, preview_latent)
  File "D:\Users\Anon\Downloads\Programs\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_tinyterraNodes\tinyterraNodes.py",
 line 762, in process_sample_state
    pipe["vars"]["samples"] = handle_upscale(pipe["vars"]["samples"], upscale_method, factor, crop)
  File "D:\Users\Anon\Downloads\Programs\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_tinyterraNodes\tinyterraNodes.py",
 line 723, in handle_upscale
    samples = upscale(samples, upscale_method, factor, crop)[0]
  File "D:\Users\Anon\Downloads\Programs\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_tinyterraNodes\tinyterraNodes.py",
 line 346, in upscale
    samples = samples[0]
KeyError: 0

```

**Comment by TinyTerra** [comment]
Newest push should also fix this

**Comment by mizukarada** [comment]
Thanks, c6c6f92e4b4a1a9d150bb24bec11bf493912c8aa fixed it. On another note, I think `bislerp` is missing?

**Comment by TinyTerra** [comment]
Bislerp has been added

**Comment by mizukarada** [comment]
Thanks
