### ISSUE TITLE
No module named 'spandrel'

### ISSUE THREAD

**Issue by curlysasha** [TinyTerra/ComfyUI_tinyterraNodes#120]
```
Traceback (most recent call last):
  File "/home/oem/ComfyUI/nodes.py", line 1879, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/oem/ComfyUI/custom_nodes/ComfyUI_tinyterraNodes/__init__.py", line 1, in <module>
    from .ttNpy.tinyterraNodes import TTN_VERSIONS
  File "/home/oem/ComfyUI/custom_nodes/ComfyUI_tinyterraNodes/ttNpy/tinyterraNodes.py", line 52, in <module>
    from spandrel import ModelLoader, ImageModelDescriptor
ModuleNotFoundError: No module named 'spandrel'

```

solved by
`pip install spandrel `

please fix

**Comment by TinyTerra** [comment]
You either need to revert ttN to a commit before https://github.com/TinyTerra/ComfyUI_tinyterraNodes/commit/bb53525551294e851f69a5195a37cc591c48bcf4

Or update comfyui
