### ISSUE TITLE
object has no attribute 'cpu'

### ISSUE THREAD

**Issue by zrll12** [TinyTerra/ComfyUI_tinyterraNodes#121]
I'm running node 'hiresfiixScale - Node Version Mismatch' using a MacBook Pro with m2max
Error:
```
!!! Exception during processing!!! 'ImageModelDescriptor' object has no attribute 'cpu'
Traceback (most recent call last):
  File "/Users/zrll/Documents/ComfyUI/execution.py", line 151, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "/Users/zrll/Documents/ComfyUI/execution.py", line 81, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "/Users/zrll/Documents/ComfyUI/execution.py", line 74, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "/Users/zrll/Documents/ComfyUI/custom_nodes/ComfyUI_tinyterraNodes/ttNpy/tinyterraNodes.py", line 3309, in upscale
    upscale_model.cpu()
AttributeError: 'ImageModelDescriptor' object has no attribute 'cpu'
```

**Comment by zrll12** [comment]
I'm using the least commit in main

**Comment by TinyTerra** [comment]
The node version mismatch in the name indicates that the node needs to be remade, if you delete it and add a new version of the same node does the error still occur?

**Comment by zrll12** [comment]
Still occurs

**Comment by TinyTerra** [comment]
This should be fixed in the latest push, please let me know if not :)

**Comment by zrll12** [comment]
It seems to be fixed
