### ISSUE TITLE
Missing TTN options on node menu

### ISSUE THREAD

**Issue by WinstonWoof** [TinyTerra/ComfyUI_tinyterraNodes#39]
Completely lost  all TTN options on node menu  when upgrading .

Even wiped completly and did full clean install.

In end reverted to older version

**Comment by CaptainGrock** [comment]
Duplicated issue - can't access these nodes

**Comment by GalaxyTimeMachine** [comment]
Same

**Comment by TinyTerra** [comment]
Is there any error log when launching comfy? 
Do the nodes fail to import, or is it just the JavaScript node options?

**Comment by GalaxyTimeMachine** [comment]
Yes...
```
Traceback (most recent call last):
  File "F:\ComfyUI\nodes.py", line 1698, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "F:\ComfyUI\custom_nodes\ComfyUI_tinyterraNodes\__init__.py", line 1, in <module>
    from .tinyterraNodes import TTN_VERSIONS
  File "F:\ComfyUI\custom_nodes\ComfyUI_tinyterraNodes\tinyterraNodes.py", line 1395
    <<<<<<< Updated upstream
    ^^
SyntaxError: invalid syntax
...
...
0.0 seconds (IMPORT FAILED): F:\ComfyUI\custom_nodes\ComfyUI_tinyterraNodes
```

**Comment by GalaxyTimeMachine** [comment]
If you saw it, please ignore the above reported error log, it was something I'd changed that caused that. I've just deleted the ttN folder and re-cloned it, and I can now see the nodes in the menu.

**Comment by WinstonWoof** [comment]
> Is there any error log when launching comfy? Do the nodes fail to import, or is it just the JavaScript node options?

no error, just MIA

**Comment by soulctcher** [comment]
This is still an issue and I've removed and re-pulled the ttn repo.  This is what's causing the failure during import on launch of ComfyUI:

`Traceback (most recent call last):
  File "C:\Users\soulc\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1694, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\soulc\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_tinyterraNodes\__init__.py", line 1, in <module>
    from .tinyterraNodes import TTN_VERSIONS
  File "C:\Users\soulc\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_tinyterraNodes\tinyterraNodes.py", line 27, in <module>
    from comfy.model_patcher import ModelPatcher
ModuleNotFoundError: No module named 'comfy.model_patcher'

Cannot import C:\Users\soulc\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_tinyterraNodes module for custom nodes: No module named 'comfy.model_patcher'`

**Comment by TinyTerra** [comment]
Please update ComfyUI using the update batch file, and check if this is still occurring.

A recent comfy update changed how certain code needed to be imported, and the current version of tinyterraNodes is no longer compatible with earlier versions of comfy ui before these changes

**Comment by soulctcher** [comment]
Looks like I had a stuck modification...forced a reset to the current comfyui commit and that resolved the issue.  Thanks @TinyTerra for your great work.
