### ISSUE TITLE
Error occurred when executing ttN pipeOUT

### ISSUE THREAD

**Issue by ervoxpin** [TinyTerra/ComfyUI_tinyterraNodes#47]
too many values to unpack (expected 9)
File "E: SDXL\ComfyUI execution.py",line 151,in recursive executeinput data all)output data, output ui = get output data(obj,File "E:\SDXL\ComfyUI\execution.py", line 81,in get output datareturn_values = map_node_over_list(obj, input_data all, obj.FUNCTION,allow interrupt=TrueFile "E:\SDXL\ComfyUI execution.py" line 74, in map node over_listresults.append(getattr(obj, func)(**slice dict(input data all, i)))File "E:\SDXL\ComfyUI\custom nodes ComfyUl tinyterraNodes\tinyterraNodes.py, line 1745,inflush
model,pos, neg, latent, vae, clip, image, seed,= pipe.values()

**Comment by lemonade10-code** [comment]
The imagebash workflow has the same basic error due to using the ttn pipeout, although mine is using a different version and so is very slightly different.
!!! Exception during processing !!!
Traceback (most recent call last):
  File "E:\ComfyUI_windows_portable\ComfyUI\execution.py", line 152, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "E:\ComfyUI_windows_portable\ComfyUI\execution.py", line 82, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "E:\ComfyUI_windows_portable\ComfyUI\execution.py", line 75, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "E:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_tinyterraNodes\tinyterraNodes.py", line 1745, in flush
    model, pos, neg, latent, vae, clip, image, seed, _ = pipe.values()
ValueError: too many values to unpack (expected 9)

**Comment by TinyTerra** [comment]
this should be fixed in 23f9005ea0420444f4da19b95ebef16081126b5f

**Comment by lemonade10-code** [comment]
Thank you, this indeed solved the problem and now the node works properly.
