### ISSUE TITLE
hiresfix

### ISSUE THREAD

**Issue by offmybach** [TinyTerra/ComfyUI_tinyterraNodes#82]
unable to locate hiresfix node anywhere. will not load in any of my workflows or the png included.

![image](https://github.com/TinyTerra/ComfyUI_tinyterraNodes/assets/137804812/99531808-6843-4682-b93f-3ef009c4babe)

**Comment by TinyTerra** [comment]
This looks as the the nodes aren't installed at all / correctly?

**Comment by offmybach** [comment]
![image](https://github.com/TinyTerra/ComfyUI_tinyterraNodes/assets/137804812/28c75cae-d2b7-4d18-a944-73caccdd9c03)

should be installed

**Comment by TinyTerra** [comment]
Does the console show [tinyterranodes] loaded on startup? Might be worthwhile deleting the entire tinyterra folder and re-installing it if not.. Not entirely sure what else could be causing it without the console log

**Comment by offmybach** [comment]
tried again and still folder present but says failed to install in manager

**Comment by TinyTerra** [comment]
Have you tried coming the repository into the custom notes folder manually, instead of via manager?

**Comment by offmybach** [comment]
Yes and this was error- which I don't understand
[tinyterraNodes] Loaded
Traceback (most recent call last):
  File "D:\ComfyUI_windows_portable\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1893, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\ComfyUI_windows_portable\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_tinyterraNodes\__init__.py", line 171, in <module>
    shutil.rmtree(web_extension_path)
  File "shutil.py", line 759, in rmtree
  File "shutil.py", line 622, in _rmtree_unsafe
  File "shutil.py", line 620, in _rmtree_unsafe
PermissionError: [WinError 5] Access is denied: 'D:\\ComfyUI_windows_portable\\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu\\ComfyUI_windows_portable\\ComfyUI\\web\\extensions\\tinyterraNodes\\ttN.js'

Cannot import D:\ComfyUI_windows_portable\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_tinyterraNodes module for custom nodes: [WinError 5] Access is denied: 'D:\\ComfyUI_windows_portable\\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu\\ComfyUI_windows_portable\\ComfyUI\\web\\extensions\\tinyterraNodes\\ttN.js'
[comfy_mtb] | INFO -> loaded 65 nodes successfuly
FaceDetailer: Model directory already exists
FaceDetailer: Model already exists
Efficiency Nodes: Attempting to add Control Net options to the 'HiRes-Fix Script' Node (comfyui_controlnet_aux add-on)...Success!
Total VRAM 8192 MB, total RAM 32433 MB
xformers version: 0.0.23.post1
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 3070 Ti Laptop GPU : cudaMallocAsync
VAE dtype: torch.bfloat16
Patching UNetModel.forward
UNetModel.forward has been successfully patched.

**Comment by TinyTerra** [comment]
Apologies for the delay on this,
It is a permission error removing the ttN web folder - that needs to be run as admin.
However i've also updated to not require this in (0f861533071b2f8ceef531a0fa892fb64fc7fd6d)

**Comment by KINGLIFER** [comment]
for some reason ttN hiresfixScale does not do anything.
